### PR TITLE
library constructor refactor

### PR DESCRIPTION
**Pull request by stormzhang**
Refactor ShimmerTextView & ShimmerButton constructor

### CODE REVIEW

**Comment by claust** [comment]
If you have the time, please consider pulling this change, @RomainPiel. I can't seem to avoid the manifest merger error.

**Comment by RomainPiel** [comment]
I don't think this PR is very consistent. I'll apply the second commit separately.

**Comment by RomainPiel** [comment]
@claust check out https://github.com/RomainPiel/Shimmer-android/commit/c11990869b40d8a0b9cf804bf0a7f78bd3b7daf5 I've just uploaded a new version 1.4.0

**Comment by claust** [comment]
Looks excellent! Thanks! Not available on the Maven repository yet, though?

**Comment by RomainPiel** [comment]
Hmm I think search.maven.com is not synced. But it's definitely up: https://repo1.maven.org/maven2/com/romainpiel/shimmer/library/

**Comment by claust** [comment]
Yep, it's available and working now. Thanks again!

**Pull request closed without merging**
